run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - node_modules
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*_gen\\.go$"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  goimports:
    local-prefixes: github.com/vzahanych/view-guard-meta
  govet:
    check-shadowing: true
  misspell:
    locale: US

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

