package types

import (
	"context"
	"time"
)

// EventBusProvider defines the interface for event bus providers.
// This allows the event bus to work with different storage backends (meta-storage, memory, NATS, etc.).
//
// Provider implementations must be thread-safe and handle concurrent operations.
// The provider is responsible for converting EventAny to the appropriate storage format
// and back. For meta-storage provider, events are stored using EventBusEventMetadata
// and EventBusFilters from the meta-storage package.
//
// # Provider Lifecycle
//
// Providers are created by the event bus implementation and their lifecycle is managed
// by the EventBus interface (Start/Stop methods). The Close() method is called during
// EventBus.Stop() to release resources.
//
// # Error Handling
//
// Providers should return descriptive errors that can be wrapped by the event bus
// implementation. Storage quota errors should be returned as-is to allow the event bus
// to implement drop policy logic.
//
// # Thread Safety
//
// All methods must be safe for concurrent use. Multiple goroutines may call these
// methods simultaneously.
type EventBusProvider interface {
	// PersistEvent persists an event to the storage backend.
	// The provider should convert EventAny to the appropriate storage format.
	//
	// The provider must:
	//   - Generate a unique event ID if not present
	//   - Store event metadata (type, source, timestamp, sequence number)
	//   - Store event data (as JSON bytes)
	//   - Handle storage quota errors appropriately
	//
	// Returns an error if:
	//   - The event is invalid (missing required fields)
	//   - Storage quota is exceeded (caller will handle drop policy)
	//   - The provider operation fails (network error, storage error, etc.)
	//
	// Example:
	//   err := provider.PersistEvent(ctx, event)
	//   if err != nil {
	//       // Handle error (may be storage quota, network error, etc.)
	//   }
	PersistEvent(ctx context.Context, event EventAny) error

	// LoadEvent loads an event by event ID from the storage backend.
	// The event ID is typically generated by the provider during PersistEvent.
	//
	// The provider must:
	//   - Look up the event by ID
	//   - Convert from storage format back to EventAny
	//   - Return nil if event does not exist (not an error)
	//
	// Returns:
	//   - The event if found
	//   - nil if the event does not exist (not an error)
	//   - An error if the provider operation fails (network error, storage error, etc.)
	//
	// Example:
	//   event, err := provider.LoadEvent(ctx, "event-123")
	//   if err != nil {
	//       // Handle error
	//   }
	//   if event == nil {
	//       // Event not found
	//   }
	LoadEvent(ctx context.Context, eventID string) (*EventAny, error)

	// ListEvents lists events matching the provided filters.
	// The provider must apply all non-nil filters to the query.
	//
	// Filter application:
	//   - EventType: Filter by exact event type match
	//   - ProcessingStatus: Filter by processing status (if supported)
	//   - From: Filter events at or after this time (inclusive)
	//   - To: Filter events at or before this time (inclusive)
	//   - Limit: Limit the number of results (if supported)
	//
	// The provider should:
	//   - Apply filters in order (EventType, ProcessingStatus, From, To, Limit)
	//   - Return events in chronological order (oldest first) if possible
	//   - Respect the Limit filter if provided
	//
	// Returns:
	//   - A slice of events matching the filters (may be empty)
	//   - An error if the provider operation fails
	//
	// Example:
	//   filters := &EventFilters{
	//       EventType: &EventTypeDeviceDiscovered,
	//       From: &startTime,
	//       To: &endTime,
	//       Limit: &limit,
	//   }
	//   events, err := provider.ListEvents(ctx, filters)
	ListEvents(ctx context.Context, filters *EventFilters) ([]EventAny, error)

	// DeleteEvent deletes an event by event ID.
	// If the event does not exist, this is a no-op and returns no error.
	//
	// The provider must:
	//   - Delete the event if it exists
	//   - Return no error if the event does not exist (idempotent)
	//   - Handle concurrent deletion gracefully
	//
	// Returns an error if:
	//   - The provider operation fails (network error, storage error, etc.)
	//
	// Example:
	//   err := provider.DeleteEvent(ctx, "event-123")
	//   if err != nil {
	//       // Handle error
	//   }
	DeleteEvent(ctx context.Context, eventID string) error

	// DeleteExpiredEvents deletes events that expired before the specified time.
	// This is used by the retention cleanup process to delete old events.
	//
	// The provider must:
	//   - Delete all events with timestamp < beforeTime
	//   - Return the count of events deleted
	//   - Handle large deletions efficiently (may be called with old timestamps)
	//
	// Implementation notes:
	//   - Should use batch deletion if possible to avoid overwhelming storage
	//   - Should be idempotent (safe to call multiple times)
	//   - May return approximate count if exact count is expensive
	//
	// Returns:
	//   - The number of events deleted (0 if none)
	//   - An error if the provider operation fails
	//
	// Example:
	//   cutoffTime := time.Now().Add(-24 * time.Hour)
	//   count, err := provider.DeleteExpiredEvents(ctx, cutoffTime)
	//   if err != nil {
	//       // Handle error
	//   }
	DeleteExpiredEvents(ctx context.Context, beforeTime time.Time) (int, error)

	// GetEventCount returns the total number of events in storage.
	// This is used for monitoring and health checks.
	//
	// The provider should:
	//   - Return an accurate count if possible
	//   - Return an approximate count if exact count is expensive
	//   - Cache the count if appropriate (with reasonable staleness)
	//
	// Returns:
	//   - The total count of events (0 if storage is empty)
	//   - An error if the provider operation fails
	//
	// Example:
	//   count, err := provider.GetEventCount(ctx)
	//   if err != nil {
	//       // Handle error
	//   }
	GetEventCount(ctx context.Context) (int, error)

	// HealthCheck performs a health check on the provider.
	// This is used by the event bus health monitoring to verify provider availability.
	//
	// The provider should:
	//   - Verify connectivity to storage backend
	//   - Perform a lightweight operation (e.g., ping, status check)
	//   - Return quickly (should not block for long)
	//
	// Returns:
	//   - An error if the provider is unhealthy (connection failed, storage unavailable, etc.)
	//   - nil if the provider is healthy
	//
	// Example:
	//   err := provider.HealthCheck(ctx)
	//   if err != nil {
	//       // Provider is unhealthy
	//   }
	HealthCheck(ctx context.Context) error

	// Close closes the provider and releases all resources.
	// This is called during EventBus.Stop() to gracefully shutdown the provider.
	//
	// The provider must:
	//   - Close all connections to storage backend
	//   - Flush any pending operations
	//   - Release all resources (goroutines, file handles, etc.)
	//   - Be idempotent (safe to call multiple times)
	//
	// Returns an error if:
	//   - Closing resources fails (should still attempt to close all resources)
	//
	// Example:
	//   err := provider.Close()
	//   if err != nil {
	//       // Log error but continue shutdown
	//   }
	Close() error
}

// EventFilters contains filters for querying events.
// All fields are optional (nil means no filter). Multiple filters are combined with AND logic.
//
// Filter application order (if multiple filters are set):
//   1. EventType (exact match)
//   2. ProcessingStatus (exact match, if supported by provider)
//   3. From (timestamp >= From)
//   4. To (timestamp <= To)
//   5. Limit (limit number of results)
//
// Example:
//   filters := &EventFilters{
//       EventType: &EventTypeDeviceDiscovered,
//       From: &startTime,
//       To: &endTime,
//       Limit: &limit,
//   }
//   events, err := provider.ListEvents(ctx, filters)
type EventFilters struct {
	// EventType filters by event type (exact match).
	// If nil, all event types are included.
	// Example: &EventTypeDeviceDiscovered
	EventType *EventType

	// ProcessingStatus filters by processing status (exact match).
	// If nil, all processing statuses are included.
	// Note: Not all providers support processing status filtering.
	// Example: &EventStatusPending
	ProcessingStatus *EventProcessingStatus

	// From filters by events occurring at or after this time (inclusive).
	// If nil, no lower bound on timestamp.
	// Example: &time.Time{...}
	From *time.Time

	// To filters by events occurring at or before this time (inclusive).
	// If nil, no upper bound on timestamp.
	// Example: &time.Time{...}
	To *time.Time

	// Limit limits the number of results returned.
	// If nil, no limit is applied (provider may have its own default limit).
	// Example: &100
	Limit *int
}

